### ISSUE TITLE
TODO before v-gamma release

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsdate#381]
We are planning a tsdate release with variational-gamma set as the default method. Here's what we need to do before release:

## Essential

- [x] Decide on which `variational_gamma` parameters (e.g. expectation iterations) should be documented, if any. FWIW my preference would be to document as few as possible, in case we change them.
- [x] Update the docs (e.g. population_size no longer needed by default)
- [x] Test the CLI and change where necessary (e.g. https://github.com/tskit-dev/tsdate/issues/377)
- [x] Add split_disjoint to preprocess_ts (https://github.com/tskit-dev/tsdate/issues/373)
- [x] Update changelog (this is a breaking change)

## Nice to have

- [ ] brief explanation of variational_gamma approach in the docs
- [ ] brief explanation of rescaling approach in the docs
- [x] Error out if no mutations in v_gamma https://github.com/tskit-dev/tsdate/issues/390#issuecomment-2148237870
- [x] #376 
- [ ] Correctly return the posterior using variational_gamma (https://github.com/tskit-dev/tsdate/issues/388)
- [ ] Add accuracy tests for `variational_gamma` (https://github.com/tskit-dev/tsdate/issues/265)
- [x] Perhaps https://github.com/tskit-dev/tsdate/issues/262 ?
- [x] Set permissive_json schema on the mutation table if it is empty and no schema is set.

## For future releases

- [ ] Unphased singletons ()
- [ ] Site masking (https://github.com/tskit-dev/tsdate/issues/315)

Does this sound right @nspope ? I will try to tick these all off in the next week or two.

**Comment by nspope** [comment]
Yes, sounds good!

**Comment by hyanwong** [comment]
Do you think any specific variational_gamma parameters should be documented, @nspope ? Are there ones that new users might need to tweak in common circumstances?

**Comment by nspope** [comment]
max_iterations (the number of EP iterations) and rescaling_intervals (which may need to be tweaked if there's weirdness like missing singletons) are the only two that come to mind?

**Comment by hyanwong** [comment]
(I guess we can also default `max_iterations` to `None`, and reserve the right to change it to something adaptive in future.

**Comment by nspope** [comment]
Sure -- I think the defaults max_shape and min_step seem to be working fine.

**Comment by hyanwong** [comment]
`min_step` isn't made available in the signature anyway.

**Comment by hyanwong** [comment]
> brief explanation of rescaling approach in the docs

This could go [here](https://tskit.dev/tsdate/docs/latest/methods.html#rescaling). If you want to provide a 2 or 3 sentence description @nspope, I'll bung it in.

**Comment by nspope** [comment]
Awesome thanks @hyanwong! I'll take a look in the next day or two.

**Comment by hyanwong** [comment]
Thanks. I'm assuming you would be happy to make a 0.2 release any time, and we can fix any doc issues later?

**Comment by nspope** [comment]
Sure, sounds good to me.
